apiVersion: v1
kind: Service
metadata:
  name:  workshop-rtp-service
  namespace: workshop
spec:
  type: NodePort
  selector:
    app: workshop-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000
